[package]
name = "jaguar-derive"
version = "1.0.0"
edition = "2021"
description = "Derive macros for Jaguar serialization"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0" }
quote = "1.0"
proc-macro2 = "1.0"
